import React, { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { X, Upload, CheckCircle2, AlertCircle, Loader2, BookOpen, User, Camera, Phone, Mail, Award, ArrowRight, Timer, Sparkles } from 'lucide-react';
import { db, auth } from '../lib/firebase';
import { doc, setDoc, serverTimestamp, runTransaction, getDoc } from 'firebase/firestore';
import { analyzePerformance, generateSubjectTest, gradeTest, generateFeedback, TestQuestion } from '../services/aiService';
import PhotoUploader from './PhotoUploader';

interface TutorApplicationWizardProps {
  isOpen: boolean;
  onClose: () => void;
}

type Step = 'INITIAL' | 'GATHER' | 'ANALYZING' | 'TEST' | 'GRADING' | 'RESULT' | 'PROFILE';

export default function TutorApplicationWizard({ isOpen, onClose }: TutorApplicationWizardProps) {
  const [step, setStep] = useState<Step>('INITIAL');
  const [subject, setSubject] = useState('');
  const [levelOfStudies, setLevelOfStudies] = useState('');
  const [experience, setExperience] = useState('');
  const [certificateProofUrl, setCertificateProofUrl] = useState<string | null>(null);
  const [performanceFile, setPerformanceFile] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [testQuestions, setTestQuestions] = useState<TestQuestion[]>([]);
  const [userAnswers, setUserAnswers] = useState<string[]>([]);
  const [finalScore, setFinalScore] = useState(0);
  const [performanceSummary, setPerformanceSummary] = useState('');
  const [feedback, setFeedback] = useState('');
  const [feedbackLoading, setFeedbackLoading] = useState(false);
  const [timeLeft, setTimeLeft] = useState(300); // 5 minutes for a real test
  const [isTimeOut, setIsTimeOut] = useState(false);
  const [profile, setProfile] = useState({
    photoUrl: '',
    phone: '',
    bio: ''
  });

  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        const dataUrl = reader.result as string;
        setPerformanceFile(dataUrl);
        setCertificateProofUrl(dataUrl);
      };
      reader.readAsDataURL(file);
    }
  };

  useEffect(() => {
    let timer: NodeJS.Timeout;
    if (step === 'TEST' && timeLeft > 0) {
      timer = setInterval(() => {
        setTimeLeft(prev => prev - 1);
      }, 1000);
    } else if (step === 'TEST' && timeLeft === 0) {
      setIsTimeOut(true);
      setStep('RESULT');
    }
    return () => clearInterval(timer);
  }, [step, timeLeft]);

  const startApplication = async () => {
    if (!subject || !levelOfStudies) return;
    setStep('ANALYZING');
    setLoading(true);
    try {
      let summary = `Applicant applying for ${subject} at ${levelOfStudies} level.`;
      if (performanceFile) {
        try {
          const res = await analyzePerformance(performanceFile);
          summary = res || summary;
        } catch (err) {
          console.error("Error analyzing performance file:", err);
        }
      }
      setPerformanceSummary(summary);

      const questions = await generateSubjectTest(subject, levelOfStudies, summary);
      if (!questions || questions.length === 0) {
        throw new Error("No test questions generated by AI");
      }
      setTestQuestions(questions);
      setUserAnswers(new Array(questions.length).fill(''));
      setTimeLeft(300); // 5 minutes (300 seconds)
      setIsTimeOut(false);
      setStep('TEST');
    } catch (err) {
      console.error("Error starting tutor application test:", err);
      alert("Failed to formulate subject competency test. Please verify the subject and try again.");
      setStep('GATHER');
    } finally {
      setLoading(false);
    }
  };

  const handleAnswerChange = (qIndex: number, answer: string) => {
    const newAnswers = [...userAnswers];
    newAnswers[qIndex] = answer;
    setUserAnswers(newAnswers);
  };

  const submitTest = async () => {
    const unansweredCount = testQuestions.filter((_, idx) => !userAnswers[idx]).length;
    if (unansweredCount > 0) {
      alert(`Please answer all questions. You have ${unansweredCount} remaining unanswered questions.`);
      return;
    }
    setStep('GRADING');
    setLoading(true);
    try {
      const score = await gradeTest(userAnswers, testQuestions);
      setFinalScore(score);
      
      // Save application record immediately with initial empty feedback
      if (auth.currentUser) {
        await setDoc(doc(db, 'tutor_applications', auth.currentUser.uid), {
          userId: auth.currentUser.uid,
          subject,
          score,
          status: score > 60 ? 'accepted' : 'rejected',
          performanceSummary,
          feedback: '',
          createdAt: serverTimestamp()
        });
      }
      
      setStep('RESULT');
      setLoading(false);

      // Fetch constructive feedback asynchronously in the background if they scored 60 or below
      if (score <= 60) {
        setFeedbackLoading(true);
        generateFeedback(subject, performanceSummary, testQuestions, userAnswers)
          .then(async (feedbackText) => {
            setFeedback(feedbackText);
            if (auth.currentUser) {
              await setDoc(doc(db, 'tutor_applications', auth.currentUser.uid), {
                feedback: feedbackText
              }, { merge: true }).catch(err => console.error("Error setting feedback", err));
            }
          })
          .catch((err) => {
            console.error(err);
            setFeedback("Please study the key areas of this subject and try applying again later.");
          })
          .finally(() => {
            setFeedbackLoading(false);
          });
      }
    } catch (err) {
      console.error(err);
      alert('Error grading test.');
      setLoading(false);
    }
  };

  const createTutorProfile = async () => {
    if (!profile.bio || !profile.phone) {
      alert('Please fill in your bio and phone number.');
      return;
    }
    const certDoc = certificateProofUrl || performanceFile;
    if (!certDoc) {
      alert('Please upload a photo scan of your official Degree or Diploma Certificate before completing registration.');
      return;
    }
    setLoading(true);
    try {
      await runTransaction(db, async (transaction) => {
        const counterRef = doc(db, 'counters', 'tutors');
        const counterSnap = await transaction.get(counterRef);
        let nextX = 1;
        if (counterSnap.exists()) {
          nextX = counterSnap.data().count + 1;
        }

        // Logic check: 2X+1=0, but X must be non-negative.
        // We will use nextX as the tutor sequence and present the "Tutor Code".
        const tutorCode = `TTR-${Math.abs(2 * nextX + 1)}`;

        if (auth.currentUser) {
          const tutorRef = doc(db, 'tutors', auth.currentUser.uid);
          transaction.set(tutorRef, {
            userId: auth.currentUser.uid,
            email: auth.currentUser.email,
            subject,
            levelOfStudies: levelOfStudies || "Bachelor's Degree",
            experience: experience || "Licensed Subject Educator",
            certificateProofUrl: certDoc,
            photoUrl: profile.photoUrl || `https://api.dicebear.com/7.x/avataaars/svg?seed=${auth.currentUser.uid}`,
            localNumber: profile.phone,
            bio: profile.bio,
            tutorCode,
            isAvailable: true,
            isDisqualified: false,
            lastWeeklyTestAt: new Date().toISOString(),
            lastWeeklyTestScore: finalScore || 80,
            createdAt: serverTimestamp()
          });
          transaction.set(counterRef, { count: nextX });
        }
      });
      alert('Tutor profile created successfully!');
      onClose();
    } catch (err) {
      console.error(err);
      alert('Error creating profile.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-[110] flex items-center justify-center p-4 bg-slate-900/80 backdrop-blur-md">
          <motion.div
            initial={{ scale: 0.9, opacity: 0, y: 20 }}
            animate={{ scale: 1, opacity: 1, y: 0 }}
            exit={{ scale: 0.9, opacity: 0, y: 20 }}
            className="bg-white w-full max-w-2xl rounded-[2.5rem] shadow-2xl overflow-hidden flex flex-col max-h-[90vh]"
          >
            {/* Header */}
            <div className="p-8 border-b border-slate-100 flex items-center justify-between bg-slate-50/50">
              <div className="flex items-center gap-4">
                <div className="p-3 bg-blue-600 rounded-2xl text-white shadow-lg shadow-blue-200">
                  <Award className="w-6 h-6" />
                </div>
                <div>
                  <h2 className="text-2xl font-bold text-slate-800 font-display">Tutor Application</h2>
                  <p className="text-sm text-slate-500">Join our community of elite educators</p>
                </div>
              </div>
              <button onClick={onClose} className="p-2 hover:bg-slate-100 rounded-full transition-colors">
                <X className="w-6 h-6 text-slate-400" />
              </button>
            </div>

            {/* Content Container */}
            <div className="flex-1 overflow-y-auto p-8">
              {step === 'INITIAL' && (
                <div className="text-center py-8">
                  <BookOpen className="w-20 h-20 text-blue-100 mx-auto mb-6" />
                  <h3 className="text-2xl font-bold text-slate-800 mb-4">Do you want to enter the app as a tutor?</h3>
                  <p className="text-slate-500 mb-8 max-w-md mx-auto">
                    Help students excel in their subjects and earn by sharing your knowledge.
                  </p>
                  <div className="flex flex-col sm:flex-row gap-4 justify-center">
                    <button 
                      onClick={() => setStep('GATHER')}
                      className="px-10 py-4 bg-blue-600 text-white font-bold rounded-2xl shadow-xl shadow-blue-200 hover:bg-blue-700 transition-all flex items-center justify-center gap-2"
                    >
                      Yes, I want to apply <ArrowRight className="w-5 h-5" />
                    </button>
                    <button 
                      onClick={() => {
                        alert('We recommend visiting our existing expert tutors for your subjects!');
                        onClose();
                      }}
                      className="px-10 py-4 bg-white border-2 border-slate-100 text-slate-600 font-bold rounded-2xl hover:bg-slate-50 transition-all"
                    >
                      No, just exploring
                    </button>
                  </div>
                </div>
              )}

              {step === 'GATHER' && (
                <div className="space-y-6">
                  <div>
                    <label className="block text-sm font-bold text-slate-700 mb-3 ml-1">What subject do you want to tutor?</label>
                    <input 
                      type="text"
                      placeholder="e.g. Advanced Mathematics, Physics, Organic Chemistry"
                      className="w-full px-6 py-4 bg-slate-50 border border-slate-100 rounded-2xl focus:outline-none focus:ring-2 focus:ring-blue-500 transition-all"
                      value={subject}
                      onChange={(e) => setSubject(e.target.value)}
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-bold text-slate-700 mb-2 ml-1">Level of Studies</label>
                    <select
                      className="w-full px-6 py-4 bg-slate-50 border border-slate-100 rounded-2xl focus:outline-none focus:ring-2 focus:ring-blue-500 transition-all font-medium text-slate-700"
                      value={levelOfStudies}
                      onChange={(e) => setLevelOfStudies(e.target.value)}
                    >
                      <option value="">Select your level of studies...</option>
                      <option value="Bachelor's Degree (B.Sc / B.A / DIPES II)">Bachelor's Degree (B.Sc / B.A / DIPES II)</option>
                      <option value="Master's Degree (M.Sc / M.A / M.Ed)">Master's Degree (M.Sc / M.A / M.Ed)</option>
                      <option value="Doctorate / PhD Degree">Doctorate / PhD Degree</option>
                      <option value="High School / GCE A-Level Educator Certificate">High School / GCE A-Level Educator Certificate</option>
                      <option value="University Undergraduate Senior">University Undergraduate Senior</option>
                      <option value="Upper Sixth / Advanced High School Diploma">Upper Sixth / Advanced High School Diploma</option>
                    </select>
                  </div>
                  <div>
                    <label className="block text-sm font-bold text-slate-700 mb-2 ml-1">Teaching & Professional Experience</label>
                    <input 
                      type="text"
                      placeholder="e.g. 4 Years GCE Board Examiner & Physics Teacher"
                      className="w-full px-6 py-4 bg-slate-50 border border-slate-100 rounded-2xl focus:outline-none focus:ring-2 focus:ring-blue-500 transition-all"
                      value={experience}
                      onChange={(e) => setExperience(e.target.value)}
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-bold text-slate-700 mb-2 ml-1">Upload Scanned Photo Proof of Degree / Certificate (Required)</label>
                    <div 
                      onClick={() => fileInputRef.current?.click()}
                      className={`border-2 border-dashed rounded-3xl p-8 text-center cursor-pointer transition-all ${certificateProofUrl || performanceFile ? 'border-emerald-500 bg-emerald-50/50' : 'border-slate-200 hover:border-blue-400 hover:bg-blue-50'}`}
                    >
                      {certificateProofUrl || performanceFile ? (
                        <div className="flex flex-col items-center">
                          <CheckCircle2 className="w-10 h-10 text-emerald-600 mb-2" />
                          <p className="text-emerald-800 font-bold text-sm">Certificate Proof Photo Uploaded Successfully!</p>
                          <p className="text-xs text-emerald-600 mt-1 font-semibold">Click to replace document scan</p>
                        </div>
                      ) : (
                        <div className="flex flex-col items-center">
                          <Upload className="w-10 h-10 text-slate-400 mb-2" />
                          <p className="text-slate-800 font-bold text-sm">Click to upload photo of Certificate or Diploma</p>
                          <p className="text-xs text-slate-400 mt-1">Upload degree, diploma, transcript, or credentials photo (JPG/PNG)</p>
                        </div>
                      )}
                    </div>
                    <input 
                      type="file"
                      hidden
                      ref={fileInputRef}
                      accept="image/*"
                      onChange={handleFileChange}
                    />
                  </div>
                  <div className="space-y-2">
                    <button 
                      disabled={!subject || !levelOfStudies}
                      onClick={startApplication}
                      className="w-full py-5 bg-blue-600 text-white font-bold rounded-2xl shadow-xl shadow-blue-200 hover:bg-[#1d4ed8] disabled:opacity-50 disabled:shadow-none transition-all cursor-pointer flex items-center justify-center gap-2"
                    >
                      <span>Launch Competency Assessment</span>
                      <ArrowRight className="w-5 h-5" />
                    </button>
                    <p className="text-[11px] text-slate-400 text-center font-semibold">
                      Note: You must score at least <strong>60%</strong> on a 10-question subject-matter competency test to be approved.
                    </p>
                  </div>
                </div>
              )}

              {step === 'ANALYZING' && (
                <div className="text-center py-16">
                  <div className="relative inline-block mb-8">
                    <div className="w-24 h-24 border-4 border-blue-600/20 border-t-blue-600 rounded-full animate-spin"></div>
                    <Award className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-8 h-8 text-blue-600" />
                  </div>
                  <h3 className="text-2xl font-bold text-slate-800 mb-4 animate-pulse">Evaluating Credentials...</h3>
                  <p className="text-slate-500 max-w-sm mx-auto">
                    Gemini AI is analyzing your academic performances to prepare a specialized assessment for you.
                  </p>
                </div>
              )}

              {step === 'TEST' && (
                <div className="space-y-8">
                  <div className="flex flex-wrap gap-3 items-center justify-between sticky top-0 bg-white/90 backdrop-blur pb-4 z-10">
                    <div className="bg-blue-50 px-6 py-3 rounded-2xl border border-blue-100 flex items-center gap-3">
                      <AlertCircle className="w-5 h-5 text-blue-600 shrink-0" />
                      <p className="text-sm text-blue-700 font-bold">Subject Competency Test: {subject}</p>
                    </div>
                    <div className="flex items-center gap-3">
                      <div className="bg-slate-50 border border-slate-150 px-6 py-3 rounded-2xl font-mono text-xs font-extrabold text-slate-600">
                        Answered: {userAnswers.filter(Boolean).length} / {testQuestions.length}
                      </div>
                      <div className={`flex items-center gap-2 px-6 py-3 rounded-2xl border font-mono font-bold ${timeLeft < 20 ? 'bg-red-50 text-red-600 border-red-100 animate-pulse' : 'bg-slate-50 text-slate-700 border-slate-100'}`}>
                        <Timer className="w-5 h-5" />
                        {Math.floor(timeLeft / 60)}:{(timeLeft % 60).toString().padStart(2, '0')}
                      </div>
                    </div>
                  </div>
                  {testQuestions.map((q, idx) => (
                    <div key={`${q.id || idx}-${idx}`} className="space-y-4">
                      <p className="text-lg font-bold text-slate-800">
                        <span className="text-blue-600 mr-2">{idx + 1}.</span> {q.question}
                      </p>
                      <div className="grid grid-cols-1 gap-3">
                        {q.options.map((opt, optIdx) => (
                          <button
                            key={optIdx}
                            onClick={() => handleAnswerChange(idx, opt)}
                            className={`px-6 py-4 text-left rounded-2xl border-2 transition-all font-medium ${userAnswers[idx] === opt ? 'border-blue-600 bg-blue-50 text-blue-800' : 'border-slate-100 hover:border-slate-200 text-slate-600'}`}
                          >
                            {opt}
                          </button>
                        ))}
                      </div>
                    </div>
                  ))}
                  <button 
                    onClick={submitTest}
                    className="w-full py-5 bg-blue-600 text-white font-bold rounded-2xl shadow-xl shadow-blue-200 hover:bg-blue-700 transition-all mt-8"
                  >
                    Submit Test for Evaluation
                  </button>
                </div>
              )}

              {step === 'GRADING' && (
                <div className="text-center py-16">
                  <Loader2 className="w-16 h-16 text-blue-600 animate-spin mx-auto mb-6" />
                  <h3 className="text-2xl font-bold text-slate-800 mb-4">Grading Your Test...</h3>
                  <p className="text-slate-500">Calculating your competency score for {subject}.</p>
                </div>
              )}

              {step === 'RESULT' && (
                <div className="text-center py-8">
                  {isTimeOut ? (
                    <motion.div initial={{ scale: 0.9, opacity: 0 }} animate={{ scale: 1, opacity: 1 }}>
                      <div className="w-24 h-24 bg-red-100 text-red-600 rounded-full flex items-center justify-center mx-auto mb-6">
                        <Timer className="w-12 h-12" />
                      </div>
                      <h3 className="text-3xl font-bold text-slate-800 mb-4">Time Expired!</h3>
                      <p className="text-slate-600 max-w-sm mx-auto mb-6 font-medium leading-relaxed">
                        NC.edu announces to you that since you did not write in the de-limited time, you've been rejected. Fail not to apply later.
                      </p>
                      <div className="bg-slate-50 border border-slate-200 p-6 rounded-3xl max-w-md mx-auto mb-6 text-center">
                        <p className="text-sm font-bold text-slate-800 mb-3">
                          Would you like to try writing a competency test in another subject instead?
                        </p>
                        <button
                          onClick={() => {
                            setSubject('');
                            setTestQuestions([]);
                            setUserAnswers([]);
                            setFinalScore(0);
                            setFeedback('');
                            setIsTimeOut(false);
                            setTimeLeft(300);
                            setStep('GATHER');
                          }}
                          className="px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-xl transition-all text-xs cursor-pointer"
                        >
                          Write Test in Another Subject
                        </button>
                      </div>
                      <button 
                        onClick={onClose}
                        className="px-10 py-4 bg-slate-800 text-white font-bold rounded-2xl hover:bg-slate-900 transition-all font-display"
                      >
                        Accept and Close
                      </button>
                    </motion.div>
                  ) : finalScore > 60 ? (
                    <motion.div initial={{ scale: 0.9, opacity: 0 }} animate={{ scale: 1, opacity: 1 }}>
                      <div className="w-24 h-24 bg-green-100 text-green-600 rounded-full flex items-center justify-center mx-auto mb-6">
                        <CheckCircle2 className="w-12 h-12" />
                      </div>
                      <h3 className="text-3xl font-bold text-slate-800 mb-2">Congratulations!</h3>
                      <p className="text-lg text-green-600 font-bold mb-4">You scored {finalScore}/100</p>
                      <p className="text-slate-600 mb-8">
                        You have been accepted as a tutor for {subject}. 
                        Your unique tutor identity code has been generated following the cryptographic protocol <strong>2X + 1 = 0</strong>. 
                        Since <strong>X</strong> must remain non-negative in our system, your secure key is:
                      </p>
                      <div className="bg-slate-50 p-6 rounded-2xl border-2 border-dashed border-blue-200 mb-8">
                        <span className="text-3xl font-mono font-bold text-blue-600 tracking-widest">
                          TTR-{Math.abs(2 * (finalScore / 10) + 1)}
                        </span>
                        <p className="text-xs text-slate-400 mt-2">Keep this code jealously; you will need it to enter the tutor section again.</p>
                      </div>
                      <button 
                        onClick={() => setStep('PROFILE')}
                        className="px-10 py-4 bg-blue-600 text-white font-bold rounded-2xl shadow-xl shadow-blue-200 hover:bg-blue-700 transition-all"
                      >
                        Create My Tutor Profile
                      </button>
                    </motion.div>
                  ) : (
                    <motion.div initial={{ scale: 0.9, opacity: 0 }} animate={{ scale: 1, opacity: 1 }}>
                      <div className="w-24 h-24 bg-red-100 text-red-600 rounded-full flex items-center justify-center mx-auto mb-6">
                        <X className="w-12 h-12" />
                      </div>
                      <h3 className="text-3xl font-bold text-slate-800 mb-2">Evaluation Incomplete</h3>
                      <p className="text-lg text-red-600 font-bold mb-4">You scored {finalScore}/100</p>
                      
                      {feedbackLoading ? (
                        <div className="bg-slate-50 p-6 rounded-3xl border border-slate-100 mb-8 text-left">
                          <h4 className="font-bold text-slate-800 mb-3 flex items-center gap-2">
                            <Sparkles className="w-4 h-4 text-blue-600 animate-pulse" />
                            AI Improvement Feedback
                          </h4>
                          <div className="flex items-center gap-3 py-2 text-slate-500 text-sm">
                            <Loader2 className="w-4 h-4 animate-spin text-blue-600" />
                            <span>Gemini is generating custom feedback to help you improve...</span>
                          </div>
                        </div>
                      ) : (
                        feedback && (
                          <div className="bg-slate-50 p-6 rounded-3xl border border-slate-100 mb-8 text-left">
                            <h4 className="font-bold text-slate-800 mb-2 flex items-center gap-2">
                              <Sparkles className="w-4 h-4 text-blue-600" />
                              AI Improvement Feedback
                            </h4>
                            <p className="text-slate-600 text-sm leading-relaxed whitespace-pre-wrap italic">
                              "{feedback}"
                            </p>
                          </div>
                        )
                      )}

                      <p className="text-slate-600 max-w-sm mx-auto mb-6">
                        Unfortunately, you have been rejected as a tutor for {subject}.
                      </p>
                      <div className="bg-slate-50 border border-slate-200 p-6 rounded-3xl max-w-md mx-auto mb-6 text-center">
                        <p className="text-sm font-bold text-slate-800 mb-3">
                          Would you like to try writing a competency test in another subject instead?
                        </p>
                        <button
                          onClick={() => {
                            setSubject('');
                            setTestQuestions([]);
                            setUserAnswers([]);
                            setFinalScore(0);
                            setFeedback('');
                            setIsTimeOut(false);
                            setTimeLeft(300);
                            setStep('GATHER');
                          }}
                          className="px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-xl transition-all text-xs cursor-pointer"
                        >
                          Write Test in Another Subject
                        </button>
                      </div>
                      <button 
                        onClick={onClose}
                        className="px-10 py-4 bg-slate-800 text-white font-bold rounded-2xl hover:bg-slate-900 transition-all"
                      >
                        Return to App
                      </button>
                    </motion.div>
                  )}
                </div>
              )}

              {step === 'PROFILE' && (
                <div className="space-y-6">
                  <div className="flex flex-col items-center mb-6">
                    <label className="block text-sm font-bold text-slate-700 mb-2 font-display text-center">
                      Upload Your Professional Tutor Photo
                    </label>
                    <p className="text-xs text-slate-400 mb-4 text-center">
                      This photo will represent you in search results seen by both students and administrators.
                    </p>
                    <PhotoUploader 
                      currentPhotoUrl={profile.photoUrl}
                      onPhotoCaptured={(base64) => setProfile(prev => ({ ...prev, photoUrl: base64 }))}
                      onClear={() => setProfile(prev => ({ ...prev, photoUrl: '' }))}
                    />
                  </div>
                  
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    <div>
                      <label className="block text-sm font-bold text-slate-700 mb-2 ml-1 flex items-center gap-2">
                        <Mail className="w-4 h-4" /> Email Address
                      </label>
                      <input 
                        type="text"
                        disabled
                        className="w-full px-6 py-4 bg-slate-50 border border-slate-100 rounded-2xl text-slate-500"
                        value={auth.currentUser?.email || ''}
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-bold text-slate-700 mb-2 ml-1 flex items-center gap-2">
                        <Phone className="w-4 h-4" /> Local Number
                      </label>
                      <input 
                        type="tel"
                        placeholder="+XX XXX XXX XXX"
                        className="w-full px-6 py-4 bg-slate-50 border border-slate-100 rounded-2xl focus:outline-none focus:ring-2 focus:ring-blue-500"
                        value={profile.phone}
                        onChange={(e) => setProfile({ ...profile, phone: e.target.value })}
                      />
                    </div>
                  </div>

                  <div>
                    <label className="block text-sm font-bold text-slate-700 mb-2 ml-1 flex items-center gap-2">
                      <User className="w-4 h-4" /> Bio (Make students interested!)
                    </label>
                    <textarea 
                      placeholder="Share your teaching style, experience, and passion..."
                      rows={4}
                      className="w-full px-6 py-4 bg-slate-50 border border-slate-100 rounded-2xl focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none"
                      value={profile.bio}
                      onChange={(e) => setProfile({ ...profile, bio: e.target.value })}
                    />
                  </div>

                  <button 
                    disabled={loading}
                    onClick={createTutorProfile}
                    className="w-full py-5 bg-blue-600 text-white font-bold rounded-2xl shadow-xl shadow-blue-200 hover:bg-blue-700 disabled:opacity-50 flex items-center justify-center gap-3"
                  >
                    {loading && <Loader2 className="w-5 h-5 animate-spin" />}
                    Complete Profile & Start Tutoring
                  </button>
                </div>
              )}
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
}
